In [19]:
import numpy as np

In [ ]:
# 引数fは最適化したい関数、init_xは初期値、step_numは勾配法の繰り返し回数

In [20]:
def gradient_descent(f, init_x, lr=0.01, step_num=100):
...     x = init_x
...
...     for i in range(step_num): # 0~100までループ
...         grad = numerical_gradient(f, x)    # 関数の勾配を求める
...         x -= lr * grad    # 勾配法の数式に当てはめる(xを勾配の方向へ移動)
...
...     return x

In [21]:
# 関数の勾配をnumerical_gradient(f, x)　で求めて、その勾配に学習率を掛けた値で更新する処理を　step_num 　で指定された回数繰り返す

In [22]:
def function_2(x):
    return x[0] ** 2 + x[1] ** 2

In [23]:
init_x = np.array([-3.0, 4.0])

In [24]:
def numerical_gradient(f, x):

    h = 1e-4 # 0.0001
    grad = np.zeros_like(x) # xと同じ形状の配列を生成

    for idx in range(x.size):
        tmp_val = x[idx]

        # f(x + h)の計算
        x[idx] = tmp_val + h
        fx_h1 = f(x)

        # f(x - h)の計算
        x[idx] = tmp_val - h
        fx_h2 = f(x)

        grad[idx] = (fx_h1 - fx_h2) / (h * 2)
        x[idx] = tmp_val # 値をもとに戻す

    return grad

In [25]:
gradient_descent(function_2, init_x = init_x, lr = 0.1, step_num = 100)

array([-6.11110793e-10,  8.14814391e-10])

In [26]:
init_x = np.array([-3.0, 4.0])

In [27]:
gradient_descent(function_2, init_x = init_x, lr = 10.0, step_num = 100)

array([-2.58983747e+13, -1.29524862e+12])

In [28]:
init_x = np.array([-3.0, 4.0])

In [30]:
gradient_descent(function_2, init_x = init_x, lr = -10., step_num = 100)

array([-2.63011810e+12,  3.08739746e+12])