In [18]:
x = np.array([0.6, 0.9])
t = np.array([0, 0, 1])

net = simpleNet()

f = lambda w: net.loss(x, t)
dW = numerical_gradient(f, net.W)

print(dW)

NameError: name 'numerical_gradient' is not defined

In [19]:
# coding: utf-8
import sys, os

In [20]:
sys.path.append(os.pardir)  # 親ディレクトリのファイルをインポートするための設定

In [21]:
import numpy as np

In [22]:
import numpy as np # softmax関数実装
def softmax(a):
    c = np.max(a)
    exp_a = np.exp(a - c) # オーバーフロー対策
    sum_exp_a = np.sum(exp_a)
    y = exp_a / sum_exp_a
    
    return y
from common.functions import softmax, cross_entropy_error

ModuleNotFoundError: No module named 'common'

In [23]:
from common.gradient import numerical_gradient

ModuleNotFoundError: No module named 'common'

In [24]:
class simpleNet:
    def __init__(self):
        self.W = np.random.randn(2,3)

    def predict(self, x):
        return np.dot(x, self.W)

    def loss(self, x, t):
        z = self.predict(x)
        y = softmax(z)
        loss = cross_entropy_error(y, t)

        return loss

# p111

In [25]:
net = simpleNet()

In [26]:
print(net.W)

[[ 0.97331442 -1.52923564  0.83629401]
 [-0.83715623  0.52699367  0.63803716]]


In [27]:
x = np.array([0.6, 0.9])

In [28]:
p = net.predict(x)

In [29]:
print(p)

[-0.16945196 -0.44324708  1.07600985]


In [30]:
t = np.array([0, 0, 1])

In [31]:
net.loss(x, t)

NameError: name 'cross_entropy_error' is not defined

In [32]:
def f(W):
    return net.loss(x, t)

In [33]:
dw = numerical_gradient(f, net.w)

NameError: name 'numerical_gradient' is not defined

In [34]:
print(dW)

NameError: name 'dW' is not defined