In [19]:
import numpy as np

In [20]:
x = np.array([1, 2])

In [21]:
x.shape

(2,)

In [22]:
W = np.array([[1, 3, 5], [2, 4, 6]])

In [23]:
print(W)

[[1 3 5]
 [2 4 6]]


In [24]:
W.shape

(2, 3)

In [25]:
Y = np.dot(x,W)

In [26]:
print(Y)

[ 5 11 17]


# p61~p63

In [36]:
x = np.array([1.0, 0.5])

In [37]:
W1 = np.array([[0.1, 0.3, 0.5], [0.2, 0.4, 0.6]])

In [38]:
B1 = np.array([0.1, 0.2, 0.3])

In [39]:
print(W1.shape)

(2, 3)


In [40]:
print(x.shape)

(2,)


In [41]:
print(B1.shape)

(3,)


In [42]:
A1 = np.dot(x, W1) + B1

In [43]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))  #sigmoid関数を定義
z1 = sigmoid(A1)

In [44]:
print(A1)

[0.3 0.7 1.1]


In [45]:
print(z1)

[0.57444252 0.66818777 0.75026011]


In [46]:
W2 = np.array([[0.1, 0.4], [0.2, 0.5], [0.3, 0.6]])

In [47]:
B2 = np.array([0.1, 0.2])

In [50]:
print(z1.shape)

(3,)


In [51]:
print(W2.shape)

(3, 2)


In [52]:
print(B2.shape)

(2,)


In [53]:
A2 = np.dot(z1, W2) + B2

In [54]:
z2 = sigmoid(A2)

In [55]:
def identity_function(x):
    return x

In [56]:
W3 = np.array([[0.1, 0.3], [0.2, 0.4]])

In [57]:
B3 = np.array([0.1, 0.2])

In [58]:
A3 = np.dot(z2, W3) + B3

In [59]:
Y = identity_function(A3)

In [60]:
print(Y)

[0.31682708 0.69627909]
